### ISSUE TITLE
Issue downloading High quality videos

### ISSUE THREAD

**Issue by HoarderofData** [sethleedy/GRC-SECURITY-NOW-PODCAST-DOWNLOAD-SCRIPT#8]
When I try to download all the high quality videos from when they first became available to up until HD became available with the following command.

`bash grc-downloader.sh -vhq -ep 239:385`

I get the following output.

`grc-downloader.sh: line 185: [: : integer expression expected
 
Seth Leedy's GRC Security Now Downloader v1.7
GitHub URL: https://github.com/sethleedy/GRC-SECURITY-NOW-PODCAST-DOWNLOAD-SCRIPT
Home URL: http://techblog.sethleedy.name/?p=24172
##########################################################
# Latest Episode: 566 Listener Feedback #236
##########################################################
 
Downloading episodes 239 to 385
 
Using compression program: bzip2
Uncompressing cache
 
Check_URL() Error: 8
URL: http://twit.cachefly.net/video/sn/sn0239/sn0239_h264m_864x480_500.mp4
You may have to turn on -skip-digital-cert-check
HQ video episode 0239 not found...
^[[B
`

**Comment by sethleedy** [comment]
Ok. Checking on it.

**Comment by sethleedy** [comment]
So, it seems some of the filenames got a change on Twit's CDN. Also, some of the files are now on a slight URL change. I'll fix up the urls, if there are more changes, let me know..
Old URL: http://twit.cachefly.net/video/sn/sn0457/sn0457_h264m_1280x720_1872.mp4
New URL: http://cdn.twit.tv/video/sn/sn0239/sn0239_h264b_864x480_500.mp4

Video # 239 on Twit: sn0239/sn0239_h264b_864x480_500.mp4
Old filename format: sn0239_h264m_864x480_500.mp4
The new one now has a letter "b" instead of a "m". Yet the new shows, # 566, does not on the HQ, but does on the SD Video Small.

Unless I can find a method to deal with the changes, I'll have to check all the different formats.

Version 1.8 coming up.

**Comment by sethleedy** [comment]
This should be resolved now.
Download version 1.8 and try it out.

I also included a new auto updater. Pass the -u switch and it should update if a new version is available.
I suggest adding it to Cron.
